name: build-and-test
on:
  workflow_dispatch:
  pull_request: { branches: [ "main" ] }
  push:        { branches: [ "main" ] }
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI OK"
